---
- name: "Run ansible roles"
  hosts: "{{ target }}"

  tasks:
    - include_role:
        name: "{{ deploy_task }}"
      loop:
        - mariadb_deploy
      loop_control:
        loop_var: deploy_task
  become: yes
